---
version: 1
formatters:
  default:
    format: '%(asctime)s %(name)s:%(lineno)s %(funcName)s [%(levelname)s]: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: ERROR
    formatter: default
    stream: ext://sys.stdout
loggers:
  default:
    level: ERROR
    handlers: [console]
    propagate: no
root:
    level: DEBUG
    handlers: [ console ]
disable_existing_loggers: False